version: "3.1"

services:
  indexer:
    build: indexer/
    environment:
      - SMR_DB_STRING='postgres://db:5432'
  search:
    build: smr/
    environment:
      - SMR_DB_STRING='postgres://db:5432'
  db:
    image: 'postgres:10'
    volumes:
      - ./db/db-init-scripts/:/docker-entrypoint-initdb.d/
      - ./db/postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
