version: "3.1"

services:
  smr:
    build:
        context: .
        dockerfile: smr/Dockerfile
    env_file:
      - conf/env.docker
    ports:
      - '8001:8001'
    volumes:
      - ./smr/bolt:/cbsmr/smr/bolt
    restart: always
  flask:
    build:
        context: .
        dockerfile: flask/Dockerfile
    env_file:
      - conf/env.docker
    volumes:
      - ./flask/socket:/cbsmr/flask/socket
    depends_on:
      - "smr"
      - "db"
      - "nginx"
    restart: always
  db:
    build:
        context: .
        dockerfile: db/Dockerfile
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
      - ./db/sql/:/docker-entrypoint-initdb.d/
      - ./db/plpyext:/db/plpyext/
      - ./smrpy:/smrpy/
    ports:
        - '5432:5432'
    restart: always
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.docker:/etc/nginx/conf.d/cbsmr.conf
      - ./flask/socket:/cbsmr/flask/socket
    ports:
      - '80:80'
    restart: always
