version: "3.1"

services:
  indexer:
    build: ./indexer
    env_file:
      - conf/env.docker
    ports:
      - '${INDEXER_PORT}:${INDEXER_PORT}'
  smr:
    build: ./smr
    env_file:
      - conf/env.docker
    ports:
      - '${SMR_PORT}:${SMR_PORT}'
    volumes:
      - '${SMR_DB_SRC_DIR}:${SMR_DB_DEST_DIR}'
    depends_on:
      - "indexer"
  flask:
    build: ./flask
    env_file:
      - conf/env.docker
    ports:
      - '${FLASK_PORT}:${FLASK_PORT}'
    depends_on:
      - "indexer"
      - "smr"
      - "db"
  db:
    image: postgres:10
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    ports:
      - '${PG_PORT}:${PG_PORT}'
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.template:/etc/nginx/conf.d/mysite.template
    ports:
      - 80
